### ISSUE TITLE
ImportError: cannot import name 'gensalt'`

### ISSUE THREAD

**Issue by RaD** [jgiannuzzi/docker-pypi-server#1]
```
$ docker logs -f mine_pypi_1
Traceback (most recent call last):
  File "/usr/local/bin/pypi-server", line 11, in <module>
    load_entry_point('pypi-server==0.3.30', 'console_scripts', 'pypi-server')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/pypi_server/server.py", line 20, in <module>
    from pypi_server.handlers.pypi.proxy.client import PYPIClient
  File "/usr/local/lib/python3.6/site-packages/pypi_server/handlers/__init__.py", line 44, in <module>
    import pypi_server.handlers.pypi
  File "/usr/local/lib/python3.6/site-packages/pypi_server/handlers/pypi/__init__.py", line 2, in <module>
    from pypi_server.handlers.pypi import simple
  File "/usr/local/lib/python3.6/site-packages/pypi_server/handlers/pypi/simple/__init__.py", line 2, in <module>
    from pypi_server.handlers.pypi.simple.packages import PackagesHandler
  File "/usr/local/lib/python3.6/site-packages/pypi_server/handlers/pypi/simple/packages.py", line 9, in <module>
    from pypi_server.db.packages import Package, PackageVersion, PackageFile
  File "/usr/local/lib/python3.6/site-packages/pypi_server/db/__init__.py", line 17, in <module>
    from .migrator.model import Migrations
  File "/usr/local/lib/python3.6/site-packages/pypi_server/db/migrator/__init__.py", line 22, in <module>
    import pypi_server.db.migrator.migrations
  File "/usr/local/lib/python3.6/site-packages/pypi_server/db/migrator/migrations/__init__.py", line 32, in <module>
    sys.modules["{}.{}".format(__name__, mod.name)] = imp.load_source(mod.name, mod.path)
  File "/usr/local/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "/usr/local/lib/python3.6/site-packages/pypi_server/db/migrator/migrations/001_create_tables.py", line 3, in <module>
    from pypi_server.db.users import Users
  File "/usr/local/lib/python3.6/site-packages/pypi_server/db/users.py", line 5, in <module>
    from playhouse.fields import gensalt, hashpw
ImportError: cannot import name 'gensalt'
```

**Comment by byronrau** [comment]
same issue, is there a fix?

**Comment by feenes** [comment]
same issue after my old virtualenv broke and I created a new virtrualenv.

However having the problem with python 2.7

**Comment by feenes** [comment]
I pip installed exactly the requirements of a two years old server on my machine and everything's working again.

so on my old machine I did a `pip freeze > frozen_requirements.txt
`and on my broken machine I did
`pip install -U -r frozen_requirements.txt`

Did not have time to identify the exact culprit

That means that some updated version of some package breaks the setup

**Comment by jgiannuzzi** [comment]
Please try again with the latest Docker image (`docker pull jgiannuzzi/pypi-server`)
